package seleniumHelper.enums;

public enum Wait {
	PRESENCE_OF_ELEMENT,
	PRESENCE_OF_ELEMENT_TEXT,
	ELEMENT_NOT_TO_BE_PRESENT,
	ELEMENT_TEXT_NOT_TO_BE_PRESENT,
	PRESENCE_OF_ATTRIBUTE,
	PRESENCE_OF_ATTRIBUTE_TEXT,
	ATTRIBUTE_NOT_TO_BE_PRESENT,
	ATTRIBUTE_TEXT_NOT_TO_BE_PRESENT,
	CLICKABILITY_OF_ELEMENT,
	COUNT_OF_ELEMENTS
}
