package seleniumHelper.enums;

public enum WaitFor {
	PRESENCE_OF_ELEMENT_OR_VALUE,
	ELEMENT_OR_VALUE_NOT_TO_BE_PRESENT,
	PRESENCE_OF_ATTRIBUTE_OR_VALUE,
	ATTRIBUTE_OR_VALUE_NOT_TO_BE_PRESENT,
	CLICKABILITY_OF_ELEMENT,
	COUNT_OF_ELEMENTS
}
